[package]
name = "executor"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = "0.32.7"
hex = "0.4.3"
primitives = { path = "../primitives" }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
