[bitcoin]
# Bitcoin network to use (mainnet, testnet, regtest)
network = "testnet"

# Bitcoin indexer URL
indexer_url = "https://mempool.space/testnet4/api"



# Watcher polling interval in seconds
polling_interval = 30

# Log level (trace, debug, info, warn, error)
log_level = "info"

# MongoDB configuration
mongodb_uri = "mongodb://localhost:27017"
database_name = "orderbook"